# Generated by Django 4.0.4 on 2023-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='Criado em ')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em ')),
            ],
        ),
    ]
