# Generated by Django 4.2.4 on 2023-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='Criado em ')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em ')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=1024, unique=True, verbose_name='<NAME>')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
