# Generated by Django 4.0.4 on 2023-08-11 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_game_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024, unique=True, verbose_name='Nome do jogo'),
            preserve_default=False,
        ),
    ]
