# Generated by Django 4.0.4 on 2023-08-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_console_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='shortName',
            field=models.CharField(default='bla', max_length=50, verbose_name='Abreviação ou Apelido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='imagem',
            field=models.ImageField(default='asd', upload_to='games', verbose_name='Capa do Jogo '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='console',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='console',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nome do console'),
        ),
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
