# Generated by Django 4.0.4 on 2023-08-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em ')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=3, verbose_name='Dificuldade do jogo')),
            ],
            options={
                'verbose_name': 'Dificuldade',
                'verbose_name_plural': 'Dificuldades',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='console',
            options={'ordering': ['name'], 'verbose_name': 'Console', 'verbose_name_plural': 'Consoles'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title'], 'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterField(
            model_name='game',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='games', verbose_name='Capa do Jogo '),
        ),
    ]
