# Generated by Django 4.0.4 on 2023-08-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_difficulty_alter_console_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='color',
            field=models.CharField(
                blank=True, max_length=15, verbose_name='Cor do console'),
        ),
        migrations.AddField(
            model_name='console',
            name='generation',
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name='Geração do console'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='api.genre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='console',
            name='shortName',
            field=models.CharField(
                blank=True, max_length=50, verbose_name='Abreviação ou Apelido'),
        ),
    ]
