# Generated by Django 4.0.4 on 2023-08-14 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.console'),
        ),
    ]
