# Generated by Django 4.0.4 on 2023-08-14 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_game_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.genre', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.console', verbose_name='Plataforma'),
        ),
    ]
